dynaconf_merge = true

[default]
API_BASE_URL = "http://www.kopis.or.kr/openApi/restful"
TIMEOUT = 30

RAW_DATA_FOLDER = "data/raw"
PREPROCESSED_DATA_FOLDER = "data/preprocessed"

PERFORMANCE_DATA_FILE = "performances_2025.csv"
PERFORMANCE_DETAILS_DATA_FILE = "performances_details_2025.csv"

KOREAN_FONT_PATH = "/System/Library/Fonts/Supplemental/AppleGothic.ttf"


[development]
DEBUG = true

[production]
DEBUG = false